お気に入り画面の新着タブのRecyclerViewとCoordinatorLayout実装
iroha-168/AndroidUITrain pull request #20
Opened 2021-10-11 13:53 UTC by nemo-855

## 概要
・お気に入り画面の新着タブのrecyclerView実装
・CoordinatorLayout上側のレイアウトにのみ適用
## 関連情報

## スクリーンショット
 | Before | After |
 | -------- | ------ |
 | <image src="" width="320">|<image src="https://user-images.githubusercontent.com/77588574/136803042-276ffd2d-a03c-4497-a554-20335002d633.mp4"  width="320"> |
## 懸念点
お気に入りの文字の大きさが少し変わるところ
２段階？のCoordinatorLayoutとRefreshLayoutが合わさっているところどうすれば良いかわからない

2021-10-15 13:27 UTC, Naoki-Hidaka requested changes

2021-10-15 13:27 UTC, Naoki-Hidaka commented on app/src/main/java/com/nemo/androiduitraining/view/fragment/favorite/FavoriteNewItemFragment.kt
> +    private fun initializeGroupieAdapter(): GroupieAdapter {
GroupAdapterはLiveDataをobserveしてupdateとかしたりするので、メソッドじゃなくて普通にインスタンス作った方がいいですね

2021-10-15 13:27 UTC, Naoki-Hidaka commented on app/src/main/java/com/nemo/androiduitraining/view/fragment/favorite/FavoriteNewItemFragment.kt
> +        val layoutManager = LinearLayoutManager(requireContext())
これは確かxmlの方で
```
app:layoutManager="androidx.recyclerview.widget.LinearLayoutManger"
```

とかできた気がする

2021-10-15 13:27 UTC, Naoki-Hidaka commented on app/src/main/java/com/nemo/androiduitraining/viewModel/favorite/FavoriteNewItemViewModel.kt
> +        FavoriteNoBrandRegistered(),
ViewModel側でViewのitemを持つのはやめたいですね

2021-10-15 13:27 UTC, Naoki-Hidaka commented on app/src/main/java/com/nemo/androiduitraining/viewModel/favorite/FavoriteNewItemViewModel.kt
> +        FavoriteNoBrandRegistered(),
ViewModel側はGroupieを使うというのを知らなくていいからですね

2021-10-15 14:47 UTC, nemo-855 commented on app/src/main/java/com/nemo/androiduitraining/viewModel/favorite/FavoriteNewItemViewModel.kt
> +        FavoriteNoBrandRegistered(),
修正しました！

2021-10-15 14:48 UTC, nemo-855 commented
FavoriteNewItemFragmentで無駄にbindingをFragmentのメンバ関数にしていたのでそこも修正しました！

2021-10-15 17:05 UTC, Naoki-Hidaka commented on app/src/main/java/com/nemo/androiduitraining/viewModel/favorite/FavoriteNewItemViewModel.kt
> +
せっかくなのでAPIから返ってきた想定でデータはこっちで持っておきましょうか

2021-10-15 17:06 UTC, Naoki-Hidaka commented on app/src/main/java/com/nemo/androiduitraining/viewModel/favorite/FavoriteNewItemViewModel.kt
> +
あと多分お気に入りのブランドがあるかないかで表示が結構変わるのでそこも実装してもらえると 🙏

2021-10-15 17:09 UTC, Naoki-Hidaka commented on app/src/main/java/com/nemo/androiduitraining/view/fragment/favorite/FavoriteNewItemFragment.kt
> +        private fun createItemCells() {
ちょっと書き方がいけてないので戻り値をListにして、updateListの方でupdate(defaultViewList + createItemCells())とかしたいですね

2021-10-15 17:10 UTC, Naoki-Hidaka commented on app/src/main/res/layout/favorite_new_item_item_cell.xml
> +        <androidx.constraintlayout.widget.Guideline
MaterialDesign的には左右16dpのmarginなんですが、16dpだと大きかったですか？

2021-10-15 17:12 UTC, Naoki-Hidaka commented on app/src/main/res/layout/favorite_new_item_item_cell.xml
> +            app:layout_constraintStart_toStartOf="@id/guideline_vertical2"
startなしで、endの制約を```guideline_vertical2```にすればこのImageViewのmarginはいらないのでは？

2021-10-15 17:13 UTC, Naoki-Hidaka commented on app/src/main/res/layout/fragment_favorite.xml
> +        android:layout_height="170dp"
ここはwrap_contentじゃダメでした？

2021-10-15 17:13 UTC, Naoki-Hidaka commented on app/src/main/res/layout/fragment_favorite.xml
> +            android:layout_height="50dp"
ditto

2021-10-15 17:14 UTC, Naoki-Hidaka commented on app/src/main/res/layout/fragment_favorite.xml
> +            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
ここの```layout_behavior```はいらないような

2021-10-15 17:14 UTC, Naoki-Hidaka commented on app/src/main/res/layout/fragment_favorite_new_item.xml
> +    <androidx.recyclerview.widget.RecyclerView
RecyclerViewしか設置しないのであれば親のConstraintLayoutはいらなそうですね

2021-10-16 02:01 UTC, nemo-855 commented on app/src/main/java/com/nemo/androiduitraining/viewModel/favorite/FavoriteNewItemViewModel.kt
> +
APIからでーた持ってきた前提に修正しました！！

お気に入りのブランドがあるところはまた長くなりそうなので別のプルリクであげます！

2021-10-16 02:14 UTC, nemo-855 commented on app/src/main/res/layout/fragment_favorite.xml
> +            android:layout_height="50dp"
上と同様に修正しました！

2021-10-16 02:28 UTC, nemo-855 commented on app/src/main/res/layout/favorite_new_item_item_cell.xml
> +            app:layout_constraintStart_toStartOf="@id/guideline_vertical2"
コンポーネントに直接marginつけるのよくないかもと思い直したので、FavoriteItemCell内部でbindのタイミングで動的に左右に16dpのmarginをセットするようにしました！

2021-10-16 02:30 UTC, nemo-855 commented on app/src/main/res/layout/favorite_new_item_item_cell.xml
> +        <androidx.constraintlayout.widget.Guideline
純粋に見逃してました！🙏

コンポーネントに直接marginつけるのよくないかもと思い直したので、FavoriteItemCell内部でbindのタイミングで動的に左右に16dpのmarginをセットするようにしました！

2021-10-16 02:31 UTC, nemo-855 commented on app/src/main/res/layout/fragment_favorite.xml
> +            app:layout_behavior="@string/appbar_scrolling_view_behavior" />
修正しました！

2021-10-16 04:44 UTC, Naoki-Hidaka commented on app/src/main/res/layout/favorite_new_item_item_cell.xml
> +        <androidx.constraintlayout.widget.Guideline
>コンポーネントに直接marginつけるのよくないかもと思い直したので

お？これはどんな理由があります？

2021-10-16 04:45 UTC, nemo-855 commented on app/src/main/res/layout/favorite_new_item_item_cell.xml
> +        <androidx.constraintlayout.widget.Guideline
純粋に同じレイアウト再利用するときに画面によってマージンが変わるかもしれないからです！ただ今回はそこまで入らない気がしますが笑

2021-10-16 04:49 UTC, Naoki-Hidaka approved these changes
長くなりましたが、対応ありがとうございました
マージンの修正だけコミットしたらマージしちゃいますね

2021-10-16 04:52 UTC, nemo-855 commented
修正しました！！

2021-10-16 05:00 UTC, merged